import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { ApplicationConfig, importProvidersFrom, provideZoneChangeDetection } from '@angular/core';
import { provideAnimations } from '@angular/platform-browser/animations';
import { provideRouter, withComponentInputBinding, withInMemoryScrolling } from '@angular/router';

import { en_US, provideNzI18n } from 'ng-zorro-antd/i18n';
import { NzIconModule } from 'ng-zorro-antd/icon';
import { NzModalModule } from 'ng-zorro-antd/modal';
import {
  ApiOutline,
  AppstoreOutline,
  ArrowDownOutline,
  ArrowLeftOutline,
  ArrowUpOutline,
  AuditOutline,
  BugOutline,
  CheckCircleOutline,
  CheckSquareOutline,
  CloseCircleOutline,
  CloseOutline,
  CloudDownloadOutline,
  CloudServerOutline,
  ClusterOutline,
  CopyOutline,
  DashboardOutline,
  DeleteOutline,
  DownOutline,
  EditOutline,
  ExperimentOutline,
  EyeInvisibleOutline,
  EyeOutline,
  FileTextOutline,
  FolderOpenOutline,
  FolderOutline,
  FormOutline,
  GithubOutline,
  GlobalOutline,
  InboxOutline,
  InfoCircleOutline,
  LinkOutline,
  LockOutline,
  LoginOutline,
  LogoutOutline,
  MailOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  PartitionOutline,
  PauseCircleOutline,
  PlayCircleOutline,
  PlusOutline,
  QuestionCircleOutline,
  ReloadOutline,
  RobotOutline,
  RocketOutline,
  SaveOutline,
  SearchOutline,
  SettingOutline,
  TeamOutline,
  ThunderboltOutline,
  UploadOutline,
  UserOutline,
  WarningOutline,
} from '@ant-design/icons-angular/icons';

import { appRoutes } from './app.routes';
import { authInterceptor } from './core/auth/auth.interceptor';
import { errorInterceptor } from './core/interceptors/error.interceptor';

const NZ_ICONS = [
  ApiOutline,
  AppstoreOutline,
  ArrowDownOutline,
  ArrowLeftOutline,
  ArrowUpOutline,
  AuditOutline,
  BugOutline,
  CheckCircleOutline,
  CheckSquareOutline,
  CloseCircleOutline,
  CloseOutline,
  CloudDownloadOutline,
  CloudServerOutline,
  ClusterOutline,
  CopyOutline,
  DashboardOutline,
  DeleteOutline,
  DownOutline,
  EditOutline,
  ExperimentOutline,
  EyeInvisibleOutline,
  EyeOutline,
  FileTextOutline,
  FolderOpenOutline,
  FolderOutline,
  FormOutline,
  GithubOutline,
  GlobalOutline,
  InboxOutline,
  InfoCircleOutline,
  LinkOutline,
  LockOutline,
  LoginOutline,
  LogoutOutline,
  MailOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  PartitionOutline,
  PauseCircleOutline,
  PlayCircleOutline,
  PlusOutline,
  QuestionCircleOutline,
  ReloadOutline,
  RobotOutline,
  RocketOutline,
  SaveOutline,
  SearchOutline,
  SettingOutline,
  TeamOutline,
  ThunderboltOutline,
  UploadOutline,
  UserOutline,
  WarningOutline,
];

export const appConfig: ApplicationConfig = {
  providers: [
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(
      appRoutes,
      withComponentInputBinding(),
      withInMemoryScrolling({
        scrollPositionRestoration: 'enabled',
        anchorScrolling: 'enabled',
      }),
    ),
    provideHttpClient(withInterceptors([authInterceptor, errorInterceptor])),
    provideAnimations(),
    provideNzI18n(en_US),
    importProvidersFrom(NzIconModule.forRoot(NZ_ICONS), NzModalModule),
  ],
};
