import {
  PageElementRecord,
} from './page-element.interface';

export type PomFramework = 'PLAYWRIGHT' | 'CYPRESS' | 'SELENIUM';

export interface PomFile {
  /** Logical class name, e.g. LoginPage. */
  className: string;
  /** File name with extension matching the framework. */
  fileName: string;
  /** Source code content. */
  content: string;
  /** Page URL the POM is built from. */
  pageUrl: string;
  /** Friendly page name (matches input or derived from URL path). */
  pageName: string;
  /** Number of elements captured on this page. */
  elementCount: number;
}

export interface PageGroup {
  pageUrl: string;
  pageName: string;
  className: string;
  elements: PageElementRecord[];
}

/**
 * Group elements into per-page buckets keyed by `pageUrl` (path-only). Pages
 * with the same URL share a Page Object even if their `pageName` differs.
 */
export const groupElementsByPage = (
  elements: PageElementRecord[],
): PageGroup[] => {
  const buckets = new Map<string, PageGroup>();
  for (const el of elements) {
    const key = canonicalPageKey(el.pageUrl);
    const existing = buckets.get(key);
    if (existing) {
      existing.elements.push(el);
      if (!existing.pageName && el.pageName) existing.pageName = el.pageName;
    } else {
      const pageName = el.pageName?.trim() || derivePageName(el.pageUrl);
      buckets.set(key, {
        pageUrl: el.pageUrl,
        pageName,
        className: toPascalCase(pageName) + 'Page',
        elements: [el],
      });
    }
  }
  return Array.from(buckets.values()).sort((a, b) =>
    a.className.localeCompare(b.className),
  );
};

export const generatePomFiles = (
  framework: PomFramework,
  groups: PageGroup[],
): PomFile[] => {
  return groups.map((g) => buildFile(framework, g));
};

const buildFile = (framework: PomFramework, g: PageGroup): PomFile => {
  if (framework === 'PLAYWRIGHT') {
    return {
      className: g.className,
      fileName: `${g.className}.ts`,
      pageUrl: g.pageUrl,
      pageName: g.pageName,
      elementCount: g.elements.length,
      content: renderPlaywright(g),
    };
  }
  if (framework === 'CYPRESS') {
    return {
      className: g.className,
      fileName: `${g.className}.js`,
      pageUrl: g.pageUrl,
      pageName: g.pageName,
      elementCount: g.elements.length,
      content: renderCypress(g),
    };
  }
  return {
    className: g.className,
    fileName: `${g.className}.java`,
    pageUrl: g.pageUrl,
    pageName: g.pageName,
    elementCount: g.elements.length,
    content: renderSelenium(g),
  };
};

const renderPlaywright = (g: PageGroup): string => {
  const fields = g.elements
    .map(
      (e) =>
        `  readonly ${safeIdent(e.elementName)}: Locator; // ${e.elementType}`,
    )
    .join('\n');
  const initializers = g.elements
    .map(
      (e) =>
        `    this.${safeIdent(e.elementName)} = page.locator(${pwSelector(e)});`,
    )
    .join('\n');
  return `import { Page, Locator } from '@playwright/test';

/**
 * Page Object: ${g.pageName}
 * URL: ${g.pageUrl}
 * Generated by AI Test Engineer.
 */
export class ${g.className} {
  readonly page: Page;
  readonly url = '${escapeSingle(g.pageUrl)}';
${fields}

  constructor(page: Page) {
    this.page = page;
${initializers}
  }

  async open(): Promise<void> {
    await this.page.goto(this.url);
  }
}
`;
};

const renderCypress = (g: PageGroup): string => {
  const methods = g.elements
    .map((e) => {
      const sel = cySelector(e);
      return `  ${safeIdent(e.elementName)}() { return cy.${sel}; } // ${e.elementType}`;
    })
    .join('\n');
  return `/**
 * Page Object: ${g.pageName}
 * URL: ${g.pageUrl}
 * Generated by AI Test Engineer.
 */
class ${g.className} {
  url = '${escapeSingle(g.pageUrl)}';

  open() { cy.visit(this.url); }

${methods}
}

module.exports = ${g.className};
`;
};

const renderSelenium = (g: PageGroup): string => {
  const fields = g.elements
    .map((e) => {
      const find = seleniumFindBy(e);
      return `    @FindBy(${find})\n    private WebElement ${safeIdent(e.elementName)}; // ${e.elementType}`;
    })
    .join('\n\n');
  const getters = g.elements
    .map(
      (e) =>
        `    public WebElement get${capitalize(safeIdent(e.elementName))}() { return ${safeIdent(e.elementName)}; }`,
    )
    .join('\n');
  return `import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;
import org.openqa.selenium.support.PageFactory;

/**
 * Page Object: ${g.pageName}
 * URL: ${g.pageUrl}
 * Generated by AI Test Engineer.
 */
public class ${g.className} {
    private final WebDriver driver;
    private final String url = "${escapeDouble(g.pageUrl)}";

${fields}

    public ${g.className}(WebDriver driver) {
        this.driver = driver;
        PageFactory.initElements(driver, this);
    }

    public void open() {
        driver.get(url);
    }

${getters}
}
`;
};

const pwSelector = (e: PageElementRecord): string => {
  switch (e.selectorType) {
    case 'XPATH':
      return `'xpath=${escapeSingle(e.selector)}'`;
    case 'TEXT':
      return `'text=${escapeSingle(e.selector)}'`;
    case 'ID':
      return `'${e.selector.startsWith('#') ? escapeSingle(e.selector) : '#' + escapeSingle(e.selector)}'`;
    default:
      return `'${escapeSingle(e.selector)}'`;
  }
};

const cySelector = (e: PageElementRecord): string => {
  switch (e.selectorType) {
    case 'XPATH':
      return `xpath('${escapeSingle(e.selector)}')`;
    case 'TEXT':
      return `contains('${escapeSingle(e.selector)}')`;
    case 'ID':
      return `get('${e.selector.startsWith('#') ? escapeSingle(e.selector) : '#' + escapeSingle(e.selector)}')`;
    default:
      return `get('${escapeSingle(e.selector)}')`;
  }
};

const seleniumFindBy = (e: PageElementRecord): string => {
  switch (e.selectorType) {
    case 'XPATH':
      return `xpath = "${escapeDouble(e.selector)}"`;
    case 'ID': {
      const id = e.selector.startsWith('#') ? e.selector.slice(1) : e.selector;
      return `id = "${escapeDouble(id)}"`;
    }
    case 'TEXT':
      return `xpath = "//*[contains(text(), '${e.selector.replace(/'/g, "\\'")}')]"`;
    default:
      return `css = "${escapeDouble(e.selector)}"`;
  }
};

export const safeIdent = (raw: string): string => {
  if (!raw) return 'element';
  let s = raw.trim();
  s = s.replace(/[^A-Za-z0-9]+/g, ' ').trim();
  if (!s) return 'element';
  const parts = s.split(/\s+/);
  const first = parts[0].toLowerCase();
  const rest = parts
    .slice(1)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1).toLowerCase());
  let ident = [first, ...rest].join('');
  if (/^\d/.test(ident)) ident = `el${ident}`;
  return ident;
};

const capitalize = (s: string): string =>
  s.length === 0 ? s : s.charAt(0).toUpperCase() + s.slice(1);

const toPascalCase = (s: string): string => {
  if (!s) return '';
  return s
    .replace(/[^A-Za-z0-9]+/g, ' ')
    .trim()
    .split(/\s+/)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1).toLowerCase())
    .join('');
};

const escapeSingle = (s: string): string => s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
const escapeDouble = (s: string): string => s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');

const canonicalPageKey = (url: string): string => {
  try {
    const u = new URL(url);
    return `${u.origin}${u.pathname}`.replace(/\/$/, '').toLowerCase();
  } catch {
    return url.toLowerCase();
  }
};

const derivePageName = (url: string): string => {
  try {
    const u = new URL(url);
    const segs = u.pathname.split('/').filter(Boolean);
    if (segs.length === 0) return 'Home';
    return segs[segs.length - 1].replace(/[-_]/g, ' ').replace(/\.[a-z]+$/i, '') || 'Home';
  } catch {
    return 'Page';
  }
};
