// =====================================================
// APP PAGES
// =====================================================

export enum EAppPage {
  LOGIN = 'LOGIN',
  DASHBOARD = 'DASHBOARD',
  FEATURE_DETAILS = 'FEATURE_DETAILS',
  SETTINGS_INTEGRATION = 'SETTINGS_INTEGRATION',
  REQUIREMENT_INPUT = 'REQUIREMENT_INPUT',
  TESTCASE_REVIEW = 'TESTCASE_REVIEW',
  REQUIREMENT_TRACEABILITY = 'REQUIREMENT_TRACEABILITY',
  PAGE_CRAWL = 'PAGE_CRAWL',
  TESTCASE_ELEMENT_MAPPING = 'TESTCASE_ELEMENT_MAPPING',
  BUILD_EXECUTION = 'BUILD_EXECUTION'
}
