import { IBaseCollection } from './IBase';
import { IReferenceInfo } from "./IReferenceInfo";

// =====================================================
// TEST CASE
// =====================================================


export interface ITestCase extends IBaseCollection {
  featureId: string; // IFeature._id
  testSuiteId: string; // ITestSuite._id

  title: string;
  description?: string;

  preconditions?: string[];
  steps: string[];
  expectedResult: string;

  /**
   * Concrete test data the tester should use to execute the case.
   * Free-form text generated by the LLM following AI_Agents Test Data
   * intelligence (valid for positive, invalid/empty/oversized for negative,
   * boundary values for boundary tests, injection payloads for security, etc.)
   */
  testData?: string;

  /**
   * Free-form feature/area tags (e.g. "Login", "Cart", "Authentication").
   * Mirrors the AI_Agents "Tags" column.
   */
  tags?: string[];

  /**
   * Optional notes / comments. Mirrors the AI_Agents "Comments" column.
   */
  comments?: string;

  /**
   * Whether this test case is suitable to be automated (stable steps,
   * deterministic expected result, no subjective UX judgement, etc.).
   * Set automatically by the LLM during generation. The "Automation"
   * string is also added to `tags` whenever this is true so other tools
   * can filter on either.
   */
  automationFeasible?: boolean;

  priority: 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
  type: 'FUNCTIONAL' | 'REGRESSION' | 'SMOKE' | 'E2E';

  status: 'GENERATED' | 'APPROVED' | 'REJECTED' | 'NEEDS_REVIEW';

  referenceInfo?: IReferenceInfo;

  createdBy: string; // IUser._id
}
